import type { Watch, SearchIndexItem } from '@/types';

export const MOCK_WATCHES: Watch[] = [
  {
    id: '1',
    name: 'Submariner Date',
    brand: 'Rolex',
    model: 'Submariner',
    reference_number: '126610LN',
    serial_number: 'SN001',
    price_cents: 1_800_000_00,
    original_price_cents: 2_000_000_00,
    currency: 'KES',
    condition: 'new',
    status: 'active',
    movement: 'automatic',
    case_material: 'Stainless Steel',
    strap_material: 'Stainless Steel Bracelet',
    case_diameter_mm: 41,
    water_resistance_m: 300,
    power_reserve_hours: 70,
    year: 2024,
    description: 'The Rolex Submariner Date in Oystersteel embodies the pinnacle of underwater watch mastery. Powered by the calibre 3235, it delivers 70 hours of precision.',
    features: ['Cerachrom bezel', 'Triplock winding crown', 'Luminescent display', 'Glidelock clasp'],
    images: [
      'https://picsum.photos/seed/rolex1/800/1000',
      'https://picsum.photos/seed/rolex2/800/1000',
      'https://picsum.photos/seed/rolex3/800/1000',
    ],
    video_url: null,
    certificate_url: null,
    stock_count: 2,
    is_featured: true,
    is_limited: false,
    tags: ['diving', 'sports', 'iconic'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Royal Oak 15500ST',
    brand: 'Audemars Piguet',
    model: 'Royal Oak',
    reference_number: '15500ST.OO.1220ST.01',
    serial_number: 'SN002',
    price_cents: 4_500_000_00,
    original_price_cents: null,
    currency: 'KES',
    condition: 'new',
    status: 'active',
    movement: 'automatic',
    case_material: 'Stainless Steel',
    strap_material: 'Stainless Steel Bracelet',
    case_diameter_mm: 41,
    water_resistance_m: 50,
    power_reserve_hours: 60,
    year: 2023,
    description: 'The Royal Oak remains the most recognizable luxury sports watch in history. Gerald Genta\'s octagonal bezel design continues to define haute horology.',
    features: ['Tapisserie dial', 'Integrated bracelet', 'Calibre 4302', 'Skeleton case back'],
    images: [
      'https://picsum.photos/seed/ap1/800/1000',
      'https://picsum.photos/seed/ap2/800/1000',
      'https://picsum.photos/seed/ap3/800/1000',
    ],
    video_url: null,
    certificate_url: null,
    stock_count: 1,
    is_featured: true,
    is_limited: true,
    tags: ['sports', 'luxury', 'collector'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Nautilus 5711',
    brand: 'Patek Philippe',
    model: 'Nautilus',
    reference_number: '5711/1A-014',
    serial_number: 'SN003',
    price_cents: 12_000_000_00,
    original_price_cents: null,
    currency: 'KES',
    condition: 'excellent',
    status: 'active',
    movement: 'automatic',
    case_material: 'Stainless Steel',
    strap_material: 'Stainless Steel Bracelet',
    case_diameter_mm: 40,
    water_resistance_m: 120,
    power_reserve_hours: 45,
    year: 2021,
    description: 'Perhaps the most coveted watch in the world. The discontinued Nautilus 5711 in steel represents the apex of horological desire, with demand far exceeding supply.',
    features: ['Olive green dial', 'Calibre 26-330 S C', 'Horizontal embossed dial', 'Graduated bezel'],
    images: [
      'https://picsum.photos/seed/pp1/800/1000',
      'https://picsum.photos/seed/pp2/800/1000',
      'https://picsum.photos/seed/pp3/800/1000',
    ],
    video_url: null,
    certificate_url: null,
    stock_count: 1,
    is_featured: true,
    is_limited: true,
    tags: ['collector', 'investment', 'rare'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Seamaster Diver 300M',
    brand: 'Omega',
    model: 'Seamaster',
    reference_number: '210.30.42.20.01.001',
    serial_number: 'SN004',
    price_cents: 65_000_00,
    original_price_cents: 75_000_00,
    currency: 'KES',
    condition: 'new',
    status: 'active',
    movement: 'automatic',
    case_material: 'Stainless Steel',
    strap_material: 'Rubber',
    case_diameter_mm: 42,
    water_resistance_m: 300,
    power_reserve_hours: 60,
    year: 2024,
    description: 'The iconic Bond watch. The Co-Axial Master Chronometer movement meets iconic design in this timeless diving companion.',
    features: ['Co-Axial escapement', 'Ceramic dial', 'Helium escape valve', 'Master Chronometer certified'],
    images: [
      'https://picsum.photos/seed/omega1/800/1000',
      'https://picsum.photos/seed/omega2/800/1000',
      'https://picsum.photos/seed/omega3/800/1000',
    ],
    video_url: null,
    certificate_url: null,
    stock_count: 5,
    is_featured: false,
    is_limited: false,
    tags: ['diving', 'sports', 'bond'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Santos de Cartier Large',
    brand: 'Cartier',
    model: 'Santos',
    reference_number: 'WSSA0018',
    serial_number: 'SN005',
    price_cents: 55_000_00,
    original_price_cents: null,
    currency: 'KES',
    condition: 'new',
    status: 'active',
    movement: 'automatic',
    case_material: 'Stainless Steel',
    strap_material: 'Alligator Leather',
    case_diameter_mm: 39.8,
    water_resistance_m: 100,
    power_reserve_hours: 38,
    year: 2024,
    description: 'Born in 1904 for aviator Alberto Santos-Dumont, the Santos remains aviation\'s most elegant companion — a masterpiece in the architecture of time.',
    features: ['QuickSwitch strap', 'SmartLink bracelet', 'Calibre 1847 MC', 'Sapphire crown'],
    images: [
      'https://picsum.photos/seed/cartier1/800/1000',
      'https://picsum.photos/seed/cartier2/800/1000',
    ],
    video_url: null,
    certificate_url: null,
    stock_count: 3,
    is_featured: false,
    is_limited: false,
    tags: ['dress', 'aviation', 'heritage'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Big Bang Unico',
    brand: 'Hublot',
    model: 'Big Bang',
    reference_number: '441.NX.1170.RX',
    serial_number: 'SN006',
    price_cents: 120_000_00,
    original_price_cents: null,
    currency: 'KES',
    condition: 'new',
    status: 'waitlist',
    movement: 'automatic',
    case_material: 'Titanium',
    strap_material: 'Rubber',
    case_diameter_mm: 42,
    water_resistance_m: 100,
    power_reserve_hours: 72,
    year: 2023,
    description: 'The Art of Fusion defines Hublot. The Big Bang Unico combines an in-house flyback chronograph with a skeletonized dial to breathtaking effect.',
    features: ['In-house UNICO movement', 'Flyback chronograph', 'Column-wheel mechanism', 'Ceramic composite case'],
    images: [
      'https://picsum.photos/seed/hublot1/800/1000',
      'https://picsum.photos/seed/hublot2/800/1000',
    ],
    video_url: null,
    certificate_url: null,
    stock_count: 0,
    is_featured: false,
    is_limited: true,
    tags: ['chronograph', 'sports', 'skeleton'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// ─── JSON Search Index ────────────────────────────────────────────
export const SEARCH_INDEX: SearchIndexItem[] = MOCK_WATCHES.map((w) => ({
  id: w.id,
  name: w.name,
  brand: w.brand,
  model: w.model,
  keywords: [
    w.name.toLowerCase(),
    w.brand.toLowerCase(),
    w.model.toLowerCase(),
    w.reference_number.toLowerCase(),
    w.movement.toLowerCase(),
    w.case_material.toLowerCase(),
    ...w.tags,
    ...w.features.map((f) => f.toLowerCase()),
  ],
  price_cents: w.price_cents,
  status: w.status,
  image: w.images[0],
}));
